# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_dXQOoKlOJMCtwMXKhqbuLxBsRRUDxf
"""

import pandas as pd
import numpy as nm
import io
import matplotlib.pyplot as mtp
import seaborn as sb
import sklearn as sk

from google.colab import files
uploaded=files.upload()

data=pd.read_csv("Social_Network_Ads.csv")
data.head()

m=data.iloc[:,[2,3]].values
n=data.iloc[:,4].values

from sklearn.model_selection import train_test_split
m_train,m_test,n_train,n_test=train_test_split(m,n,test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler
st_m=StandardScaler()
m_train= st_m.fit_transform(m_train) 
m_test= st_m.transform(m_test)

from sklearn.linear_model import LogisticRegression  
classifier= LogisticRegression(random_state=0)  
classifier.fit(m_train, n_train)

from matplotlib.colors import ListedColormap  
x_set, y_set = m_train, n_train  
x1, x2 = nm.meshgrid(nm.arange(start = x_set[:, 0].min() - 1, stop = x_set[:, 0].max() + 1, step  =0.01),  
nm.arange(start = x_set[:, 1].min() - 1, stop = x_set[:, 1].max() + 1, step = 0.01))  
mtp.contourf(x1, x2, classifier.predict(nm.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),  
alpha = 0.75, cmap = ListedColormap(('purple','green' )))  
mtp.xlim(x1.min(), x1.max())  
mtp.ylim(x2.min(), x2.max())  
for i, j in enumerate(nm.unique(y_set)):  
    mtp.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1],  
        c = ListedColormap(('purple', 'green'))(i), label = j)  
mtp.title('Logistic Regression (Training set)')  
mtp.xlabel('Age')  
mtp.ylabel('Estimated Salary')  
mtp.legend()  
mtp.show()

n



m